<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\DoctorLoan.Application\DoctorLoan.Application.csproj" />
    <ProjectReference Include="..\DoctorLoan.MedicalRecord.Application\DoctorLoan.MedicalRecord.Application.csproj" />
  </ItemGroup>

</Project>
