<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="Const\Emails\**" />
        <Compile Remove="Const\SMSs\**" />
        <Compile Remove="Models\**" />
        <EmbeddedResource Remove="Const\Emails\**" />
        <EmbeddedResource Remove="Const\SMSs\**" />
        <EmbeddedResource Remove="Models\**" />
        <None Remove="Const\Emails\**" />
        <None Remove="Const\SMSs\**" />
        <None Remove="Models\**" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MediatR" Version="12.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="7.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.5" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.3" />
    </ItemGroup>
</Project>
